export interface paymentInterface {
    Semesteran?: number,
    UP?: number,
    UAS?: number,
    UTS?: number,
    Sertifikasi?: number,
    PKKMB?: number,
    Kantin?: number,
    bank_code?: string,
    account_number?: any,
    amount?: number,
    description?: string,
    note_Semesteran?: string,
    note_UAS?: string,
    note_UTS?: string,
    note_PKKMB?: string,
    note_Kantin?: string,
    note_UP?: string,
    note_Sertifikasi?: string
}